openapi: 3.0.1
info:
  title: Swagger Zombie
  contact:
    email: apiteam@swagger.io
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: zombies
    description: Everything about your Zombies
paths:
  /zombie:
    get:
      tags:
        - zombies
      summary: Get zombies
      operationId: getZombies
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zombie'
    
    post:
      tags:
        - zombies
      summary: Post zombie
      operationId: postZombie
      requestBody:
        description: Zombie object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zombie'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ApiResponse'
    
  /zombie/{zombieId}:
      get:
        tags:
          - zombies
        summary: Get zombie
        operationId: getZombie
        parameters:
          - name: zombieId
            in: path
            description: ID of zombie to return
            required: true
            schema:
              type: string
        responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/Zombie'
      put:
        tags:
          - zombies
        summary: Put zombie
        operationId: postZombie
        parameters:
          - name: zombieId
            in: path
            description: ID of zombie to return
            required: true
            schema:
              type: string
        requestBody:
          description: Zombie object that needs to be added to the store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zombie'
          required: true
        responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/ApiResponse'

      delete:
        tags:
          - zombies
        summary: Delete zombie
        operationId: deleteZombie
        parameters:
          - name: zombieId
            in: path
            description: ID of zombie to return
            required: true
            schema:
              type: string
        responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/ApiResponse'
  /zombie/{zombieId}/items:
    get:
      tags:
        - zombies
      summary: Get zombie items
      operationId: getZombieItems
      parameters:
        - name: zombieId
          in: path
          description: ID of zombie to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResponse'

    post:
      tags:
        - zombies
      summary: Post zombie items
      operationId: postZombieItems
      parameters:
        - name: zombieId
          in: path
          description: ID of zombie to return
          required: true
          schema:
            type: string
      requestBody:
        description: Zombie object that needs to be added to the store
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Item'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ApiResponse'
    patch:
      tags:
        - zombies
      summary: Remove zombie items
      operationId: patchZombieItems
      parameters:
        - name: zombieId
          in: path
          description: ID of zombie to return
          required: true
          schema:
            type: string
      requestBody:
        description: Zombie object that needs to be added to the store
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Item'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ApiResponse'

components:
  schemas:
    Zombie:
      type: object
      properties:
        name:
          type: string
          example: Zombie 1
        creationDate:
          type: string
          example: '2020-03-12'

    Item:
      type: object
      properties:
        name:
          type: string
          example: Item 1
        value:
          type: number
          example: 7

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: OK
